my_app/models.py
from sqlalchemy import ForeignKey
from my_app import db

class Product():
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    price = db.Column(db.Float)
    category_id = db.Column(db.Integer, ForeignKey('category.id'))
    categories = db.relationship('Category', backref=db.backref('products', lazy='dynamic'))

    def __init__(self, name, price, category):
        self.name = name
        self.price = price
        self.category = category

    def __repr__(self):
        return '<Product %d.>' % self.id



class Category():
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30))

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return '<Category %d.>' % self.id

my_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////tmp/test.db' 
db = SQLAlchemy(app) 

db = SQLAlchemy(app)

from my_app.views import catalog
app.register_blueprint(catalog)

db.create_all()

my_app/views.py
from my_app import db, app
from flask import Blueprint, render_template, request
from my_app.models import Product, Category

catalog = Blueprint('catalog',__name__)

@app.errorhandler(404)  #should be "app", not "catalog" for error handling
def page_not_found(e): 
    return render_template('404.html'), 404 

@catalog.route('/')
@catalog.route('/home')
def home():
    return render_template('home.html')


@catalog.route('/product/<id>')
def product(id):
    Product.query.get_or_404(id)
    return render_template('product', product=product)


@catalog.route('/products')
@catalog.route('/products/<int:page>')
def products(page=1):
    products = Product.query.paginate(page, 10).items
    return render_template('products.html', products=products)


@catalog.route('/product-create', methods=['POST',])
def create_product():
    name = request.form.get('name')
    price = request.form.get('price')
    product = Product(name, price)
    db.session.add(product)
    db.session.commit()
    return render_template('product.html', product=product)


@catalog.route('/category-create', methods=['POST',])
def create_category():
    name = request.form.get('name')
    category = Category(name)
    db.session.add(category)
    db.session.commit()
    return render_template('category.html', category=category)


@catalog.route('/category/<id>')
def category(id):
    category = Category.query.get_or_404(id)
    return render_template('category.html', category=category)


@catalog.route('/categories')
def categories():
    categories = Category.query.all()
    return render_template('categories.html', categories=categories)

my_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Framework Cookbook</title>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{{ url_for('catalog.home') }}">Flask Cookbook</a>
        </div>
      </div>
    </div>
    <div class="container">
    {% block container %}{% endblock %}
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
  </body>
</html>

my_app/templates/categories.html
{% extends 'home.html' %} 
 
{% block container %} 
  <div class="top-pad"> 
    {% for category in categories %} 
    <a href="{{ url_for('catalog.category', id=category.id) }}"> 
      <h2>{{ category.name }}</h2> 
    </a> 
    {% endfor %} 
  </div> 
{% endblock %} 

my_app/templates/category.html
{% extends 'home.html' %} 
 
{% block container %} 
  <div class="top-pad"> 
    <h2>{{ category.name }}</h2> 
    <div class="well"> 
      {% for product in category.products %} 
        <h3> 
          <a href="{{ url_for('catalog.product', id=product.id) }}">
          {{ product.name }}</a> 
          <small>$ {{ product.price }}</small> 
        </h3> 
      {% endfor %} 
    </div> 
  </div> 
{% endblock %} 

my_app/templates/home.html
{% extends 'base.html' %} 
 
{% block container %} 
  <h1>Welcome to the Catalog Home</h1> 
  <a href="{{ url_for('catalog.products') }}">Click here to see 
     the catalog</a> 
{% endblock %} 

my_app/templates/product.html
{% extends 'home.html' %} 
 
{% block container %} 
  <div class="top-pad"> 
    <h1>{{ product.name }}<small> {{ product.category.name 
       }}</small></h1> 
    <h3>{{ product.price }}</h3> 
  </div> 
{% endblock %} 

my_app/templates/products.html
{% extends 'home.html' %} 
 
{% block container %} 
  <div class="top-pad"> 
    {% for product in products.items %} 
      <div class="well"> 
        <h2> 
          <a href="{{ url_for('catalog.product', id=product.id) 
             }}">{{ product.name }}</a> 
          <small>$ {{ product.price }}</small> 
        </h2> 
      </div> 
    {% endfor %} 
    {% if products.has_prev %} 
      <a href="{{ url_for(request.endpoint, page=products.prev_num) }}"> 
        {{"<< Previous Page"}} 
      </a> 
    {% else %} 
      {{"<< Previous Page"}} 
    {% endif %} | 
    {% if products.has_next %} 
      <a href="{{ url_for(request.endpoint, page=products.next_num) }}"> 
        {{"Next page >>"}} 
      </a> 
    {% else %} 
      {{"Next page >>"}} 
    {% endif %} 
  </div> 
{% endblock %} 